### ISSUE TITLE
最近还在写 iOS 吗

### ISSUE THREAD

**Issue by MrPans** [xiao333ma/Friday_iOS#1]
Hi
最近还在写 iOS 吗？ 看过你 2 年前写的博客觉得很不错，考虑来阿里巴巴工作吗？

**Comment by xiao333ma** [comment]
> Hi
> 最近还在写 iOS 吗？ 看过你 2 年前写的博客觉得很不错，考虑来阿里巴巴工作吗？

@saildog 还在写，多谢垂青，可以加个好友么 😄

**Comment by MrPans** [comment]
请加我微信 414457254
